### PR TITLE
Add downscript to fix free_machine targets

### PR DESCRIPTION
**Pull request by robertvolkmann**
## Description

None

### CODE REVIEW

**Comment by robertvolkmann** [comment]
@Gerrit91 could you test?

**Comment by Gerrit91** [comment]
Don't exactly understand why but to me it does not work:

```
❯ make free-machine01
...
docker exec vms /mini-lab/manage_vms.py --names machine01 kill --with-disks
docker exec vms /mini-lab/manage_vms.py --names machine01 create
Formatting '/machine01.img', fmt=qcow2 size=5368709120 cluster_size=65536 lazy_refcounts=off refcount_bits=16
qemu-system-x86_64 -name machine01 -uuid e0ab02d2-27cd-5a5e-8efc-080ba80cf258 -m 2G -boot n -cpu host -drive if=virtio,format=qcow2,file=/machine01.img -drive if=pflash,format=raw,readonly,file=/usr/share/OVMF/OVMF_CODE.fd -drive if=pflash,format=raw,readonly,file=/usr/share/OVMF/OVMF_VARS.fd -serial telnet:127.0.0.1:4000,server,nowait -enable-kvm -nographic -device virtio-net,netdev=hn0,mac=aa:c1:ab:a2:e8:bd -netdev tap,id=hn0,ifname=tap0,script=/mini-lab/mirror_tap_to_lan.sh,downscript=/mini-lab/remove_mirror.sh -device virtio-net,netdev=hn1,mac=aa:c1:ab:18:a2:da -netdev tap,id=hn1,ifname=tap1,script=/mini-lab/mirror_tap_to_lan.sh,downscript=/mini-lab/remove_mirror.sh &
Error: Exclusivity flag on, cannot modify.
qemu-system-x86_64: network script /mini-lab/mirror_tap_to_lan.sh failed with status 512
```

But if I do it manually, it works:

```

❯ docker exec -it d198f8849b8e bash
root@vms:/# tc qdisc del dev lan0 ingress
root@vms:/# tc qdisc del dev lan1 ingress
root@vms:/# exit 
exit
❯ make free-machine01
...
docker exec vms /mini-lab/manage_vms.py --names machine01 kill --with-disks
docker exec vms /mini-lab/manage_vms.py --names machine01 create
Formatting '/machine01.img', fmt=qcow2 size=5368709120 cluster_size=65536 lazy_refcounts=off refcount_bits=16
qemu-system-x86_64 -name machine01 -uuid e0ab02d2-27cd-5a5e-8efc-080ba80cf258 -m 2G -boot n -cpu host -drive if=virtio,format=qcow2,file=/machine01.img -drive if=pflash,format=raw,readonly,file=/usr/share/OVMF/OVMF_CODE.fd -drive if=pflash,format=raw,readonly,file=/usr/share/OVMF/OVMF_VARS.fd -serial telnet:127.0.0.1:4000,server,nowait -enable-kvm -nographic -device virtio-net,netdev=hn0,mac=aa:c1:ab:a2:e8:bd -netdev tap,id=hn0,ifname=tap0,script=/mini-lab/mirror_tap_to_lan.sh,downscript=/mini-lab/remove_mirror.sh -device virtio-net,netdev=hn1,mac=aa:c1:ab:18:a2:da -netdev tap,id=hn1,ifname=tap1,script=/mini-lab/mirror_tap_to_lan.sh,downscript=/mini-lab/remove_mirror.sh &
QEMU 4.2.1 monitor - type 'help' for more information
(qemu) 
```

**Comment by Gerrit91** [comment]
Don't you see the same behavior? If so, maybe we need to execute the commands outside the downscript.

**Comment by robertvolkmann** [comment]
Sending `SIGKILL` to the QEMU processes prevents the downscript from executing. It has been changed to `SIGTERM`.

**Review by Gerrit91 — APPROVED** [review]

**Comment by Honigeintopf** [comment]
Really nice !

**Pull request merged**
