### PR TITLE
Add comment to docs when running `make route` target

### PR DESCRIPTION
**Pull request by LimKianAn**
The `nexthop`s change every time if we do a brand new `make` and if you want to add the new routes, it just tells you it already exists. Now, the description of this catch is added to *README*.

### CODE REVIEW

**Comment by GrigoriyMikhalkin** [comment]
IMO, too mouthfull) I would write something like:
> add this route to communicate with the virtual internet network 100.255.254.0/24 over leaf01 and leaf02.  Route should be refreshed each time mini-lab is rebooted.

**Comment by Gerrit91** [comment]
I think with #61 the behavior changed a bit and the text needs to be adapted.

**Comment by Gerrit91** [comment]
If there's no progress going on in this issue, I'll close this in the near future.

**Review by Gerrit91 — APPROVED** [review]

**Comment by Gerrit91** [comment]
Thanks, @LimKianAn

**Pull request merged**
