### PR TITLE
Switch to tc mirrored to get rid of macvtap

### PR DESCRIPTION
**Pull request by robertvolkmann**
It's essential to set the MAC address of the virtual network device equal to the corresponding lan device. Otherwise, only one of the machines can boot successfully via PXE, as already observed in PR #96.

### CODE REVIEW

**Comment by robertvolkmann** [comment]
@GrigoriyMikhalkin What is your opinion?

**Comment by GrigoriyMikhalkin** [comment]
> @GrigoriyMikhalkin What is your opinion?

At the moment it's unclear if there's any benefits of using tc mirred vs macvtap.

**Comment by mwindower** [comment]
Nice! I would assume that tc is also faster. Could you do a performance test/iperf btw. machines?

**Comment by robertvolkmann** [comment]
I tested performance between machines and observed no differences between macvtap and tc-redirect.

**Review by Gerrit91 — APPROVED** [review]

**Pull request merged**
