### PR TITLE
SONiC

### PR DESCRIPTION
**Pull request by robertvolkmann**

### CODE REVIEW

**Comment by GrigoriyMikhalkin** [comment]
Just a comment on a general direction. Maybe we should expand mini-lab flavors that we already have with SONiC. At the moment flavors only supposed to change number of VMs for machines. But they could be used to switch between Cumulus and SONiC labs as well.

**Comment by mwindower** [comment]
@robertvolkmann could you document with a comment what is already working and what is not?

**Comment by GrigoriyMikhalkin** [comment]
@robertvolkmann I think we can close this one in favor of https://github.com/metal-stack/mini-lab/pull/127

**Comment by Gerrit91** [comment]
Resolved by #153.

**Pull request closed without merging**
