### PR TITLE
explain virtual network requirement

### PR DESCRIPTION
**Pull request by kolsa**

### CODE REVIEW

**Comment by Gerrit91** [comment]
Would this have an influence on https://github.com/metal-stack/mini-lab/issues/5 as well?

**Comment by mwindower** [comment]
It would be nicer if we could check if the network is defined by `virsh net-dumpxml vagrant-libvirt` and if this is not the case: create it. Both can happen directly at startup as one of the make targets.

@kolsa wdyt?

**Comment by kolsa** [comment]
I like!  
What about virbr1? We should be careful there too

**Comment by Gerrit91** [comment]
I think this should not be required anymore with #17. I will close this, please re-open when you think that this is still relevant.

**Pull request closed without merging**
